<?php

return [
    'tabs' => [
      'setup'                 => 'Setup',
      'sitemap'               => 'Sitemap',
      'google-search-console' => 'Google Search Console',
      'ahrefs'                => 'Ahrefs',
      // 'aggregation'           => 'Aggregation',
      'screaming_frogs'       => 'Screaming Frog Crawl',
      'sem-rush'              => 'SEM Rush'
    ],
    'screaming_frogs' => [
      'address'                        => 'Address',
      'content'                        => 'Content',
      'status_code'                    => 'Status Code',
      'status'                         => 'Status',
      'indexability'                   => 'Indexability',
      'indexability_status'            => 'Indexability Status',
      'title_1'                        => 'Title 1',
      'title_1_length'                 => 'Title 1 Length',
      'title_1_pixel_width'            => 'Title 1 Pixel Width',
      'meta_description_1'             => 'Meta Description 1',
      'meta_description_1_length'      => 'Meta Description 1 Length',
      'meta_description_1_pixel_width' => 'Meta Description 1 Length',
      'meta_keyword_1'                 => 'Meta Keyword 1',
      'meta_keywords_1_length'         => 'Meta Keywords 1 Length',
      'h1_1'                           => 'H1 1',
      'h1_1_length'                    => 'H1 1 Length',
      'h1_2'                           => 'H1 1 Length',
      'h1_2_length'                    => 'H1 1 Length',
      'h2_1'                           => 'H2 1',
      'h2_1_length'                    => 'H2 1 Length',
      'h2_2'                           => 'H2 2',
      'h2_2_length'                    => 'H2 2 Length',
      'meta_robots_1'                  => 'Meta Robots 1',
      'x_robots_tag_1'                 => 'X Robots Tag 1',
      'meta_refresh_1'                 => 'Meta Refresh 1',
      'canonical_link_element_1'       => 'Canonical Link Element 1',
      'relnext_1'                      => 'Relnext 1,',
      'relprev_1'                      => 'Relprev 1',
      'http_relnext_1'                 => 'Http Relnext 1',
      'http_relprev_1'                 => 'Http Relprev 1',
      'size_bytes'                     => 'Size Bytes',
      'word_count'                     => 'Word Count',
      'text_ratio'                     => 'Text Ratio',
      'crawl_depth'                    => 'Crawl Depth',
      'link_score'                     => 'Link Score',
      'inlinks'                        => 'Link Score',
      'unique_inlinks'                 => 'Link Score',
      'percentage_of_total'            => '% Of Total',
      'outlinks'                       => 'Outlinks',
      'unique_outlinks'                => 'Unique Outlinks',
      'external_outlinks'              => 'External Outlinks',
      'unique_external_outlinks'       => 'Unique External Outlinks',
      'hash'                           => 'Hash',
      'response_time'                  => 'Response Time',
      'last_modified'                  => 'Last Modified',
      'redirect_url'                   => 'Redirect Url',
      'redirect_type'                  => 'Redirect Type',
      'url_encoded_address'            => 'Url Encoded Address',
    ],
    'sum_rush' => [
        'url'                      =>  'Url',
        'keyword'                  =>  'Keyword',
        'position'                 =>  'Position',
        'previous_position'        =>  'Previous Position',
        'search_volume'            =>  'Search volume',
        'keyword_difficulty'       =>  'Keyword Difficulty',
        'cpc'                      =>  'CPC',
        'traffic'                  =>  'Traffic',
        'traffic_percentage'       =>  'Traffic (%)',
        'traffic_cost'             =>  'Traffic Cost',
        'competition'              =>  'Competition',
        'number_of_results'        =>  'Number Of Results',
        'trends'                   =>  'Trends',
        'timestamp'                =>  'Timestamp',
        'serp_features_by_keyword' =>  'Serp Features By Keyword',

    ]
];
